### ISSUE TITLE
flaky hyrax/dashboard_controller spec

### ISSUE THREAD

**Issue by rococodogs** [LafayetteCollegeLibraries/spot#968]
(heads-up: this is occurring on the [`ruby-hyrax-upgrade`](https://github.com/LafayetteCollegeLibraries/spot/tree/ruby-hyrax-upgrade) branch which upgrades Hyrax to 3.x stable)

this only fails once in a while?

<img width="1249" alt="Screen Shot 2022-11-09 at 3 19 30 PM" src="https://user-images.githubusercontent.com/2744987/200933546-ba97c281-f344-409a-9db1-da0f378118d3.png">

**Comment by rococodogs** [comment]
stacktrace from [latest failure](https://app.circleci.com/pipelines/github/LafayetteCollegeLibraries/spot/2172/workflows/0266ddd5-61fc-413f-97b1-46ee8c83b2d8/jobs/8055):

(source for top: https://github.com/samvera/hyrax/blob/3.x-stable/app/models/hyrax/statistic.rb#L51)

```
Failure/Error: render 'show_admin'

ActionView::Template::Error:
  undefined method `join' for nil:NilClass
./vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-65a7f247cf7e/app/models/hyrax/statistic.rb:51:in `block in work_types'
./vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-65a7f247cf7e/app/models/hyrax/statistic.rb:51:in `each'
./vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-65a7f247cf7e/app/models/hyrax/statistic.rb:51:in `group_by'
./vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-65a7f247cf7e/app/models/hyrax/statistic.rb:51:in `work_types'
./vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-65a7f247cf7e/app/views/hyrax/dashboard/_work_type_graph.html.erb:7:in `_vendor_bundle_ruby_______bundler_gems_hyrax___a_f___cf_e_app_views_hyrax_dashboard__work_type_graph_html_erb___3507059793336652558_735080'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/template.rb:159:in `block in render'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `block in instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/template.rb:354:in `instrument_render_template'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/template.rb:157:in `render'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `block in instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/partial_renderer.rb:312:in `render'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/renderer.rb:49:in `render_partial'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/helpers/rendering_helper.rb:36:in `render'
./vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-65a7f247cf7e/app/views/hyrax/dashboard/show_admin.html.erb:43:in `_vendor_bundle_ruby_______bundler_gems_hyrax___a_f___cf_e_app_views_hyrax_dashboard_show_admin_html_erb__3142736571157741013_734860'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/template.rb:159:in `block in render'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `block in instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/template.rb:354:in `instrument_render_template'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/template.rb:157:in `render'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `block in instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/template_renderer.rb:16:in `render'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/renderer.rb:44:in `render_template'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/renderer/renderer.rb:25:in `render'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/rendering.rb:103:in `_render_template'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/streaming.rb:219:in `_render_template'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/rendering.rb:84:in `render_to_body'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/abstract_controller/rendering.rb:25:in `render'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/rendering.rb:36:in `render'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/usr/local/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
./vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.7.1/lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/instrumentation.rb:45:in `render'
./app/controllers/hyrax/dashboard_controller.rb:32:in `show'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/abstract_controller/base.rb:194:in `process_action'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `block in instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:168:in `instrument'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
./vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.7.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/abstract_controller/base.rb:134:in `process'
./vendor/bundle/ruby/2.7.0/gems/actionview-5.2.7.1/lib/action_view/rendering.rb:32:in `process'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/metal.rb:191:in `dispatch'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/test_case.rb:517:in `process'
./vendor/bundle/ruby/2.7.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
./vendor/bundle/ruby/2.7.0/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:35:in `block in process'
./vendor/bundle/ruby/2.7.0/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:104:in `catch'
./vendor/bundle/ruby/2.7.0/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:104:in `_catch_warden'
./vendor/bundle/ruby/2.7.0/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:35:in `process'
./vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.7.1/lib/action_controller/test_case.rb:395:in `get'
./vendor/bundle/ruby/2.7.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
./spec/controllers/hyrax/dashboard_controller_spec.rb:7:in `block (2 levels) in <top (required)>'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:365:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `each'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `reverse_each'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:484:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:505:in `run_before_example'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:261:in `block in run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
./vendor/bundle/ruby/2.7.0/gems/rspec-rails-5.1.2/lib/rspec/rails/example/controller_example_group.rb:192:in `block (2 levels) in <module:ControllerExampleGroup>'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
./vendor/bundle/ruby/2.7.0/gems/rspec-rails-5.1.2/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
./vendor/bundle/ruby/2.7.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.0/exe/rspec:4:in `<top (required)>'
./vendor/bundle/ruby/2.7.0/bin/rspec:25:in `load'
./vendor/bundle/ruby/2.7.0/bin/rspec:25:in `<top (required)>'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
./vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
------------------
--- Caused by: ---
NoMethodError:
  undefined method `join' for nil:NilClass
  ./vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-65a7f247cf7e/app/models/hyrax/statistic.rb:51:in `block in work_types'
```
